version: "2"
services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile-development
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
      - $SSH_AUTH_SOCK:/ssh-agent # Forward local machine SSH key to docker
    env_file:
        - ./app/env/.env
    environment:
        SSH_AUTH_SOCK: /ssh-agent

  mysql:
    image: mariadb:10.3.4
    ports:
        - 3306:3306
    volumes:
        - ./data/mariadb:/var/lib/mysql
    env_file:
        - ./app/env/.env

  redis:
    image: redis:3.2.11
